Traceback (most recent call last):
  File "/home/bitzer/SoftDev/Python/virtEnv/SE/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/bitzer/SoftDev/Python/virtEnv/SE/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/bitzer/SoftDev/Python/virtEnv/SE/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/bitzer/SoftDev/Python/virtEnv/SE/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/bitzer/SoftDev/Python/virtEnv/SE/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/bitzer/SoftDev/Python/virtEnv/SE/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/bitzer/SoftDev/Python/virtEnv/SE/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# -*- coding: utf-8 -*-
#-------------------------------------------------------------------------------
# Demoscript for "Signalverarbeitung 1"
#
# Version: 1.0   17.02.2022
# 
# This software is released as public domain under CC0 1.0
# https://creativecommons.org/publicdomain/zero/1.0/
#-------------------------------------------------------------------------------

import yfinance
import matplotlib
from matplotlib import pyplot

try: 
    if get_ipython().__class__.__name__ == 'ZMQInteractiveShell':
        prefix = ''
except:
    prefix = '../../'

matplotlib.style.use(f'{prefix}sv.mplstyle')

dax = yfinance.Ticker("DAX") # chooses the DAX stock
data = dax.history(period="1wk") # gets course data as pandas Dataframe
close = data[["Close"]] # selects the Close coulumn in the Dataframe
close.plot(marker='X', color='black')

# glue this figure to paste it later (no effect outside of MyST NB)
from myst_nb import glue
glue("daxkurs", pyplot.gcf(), display=False)

pyplot.show()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn [2], line 11[0m
[1;32m      1[0m [38;5;66;03m# -*- coding: utf-8 -*-[39;00m
[1;32m      2[0m [38;5;66;03m#-------------------------------------------------------------------------------[39;00m
[1;32m      3[0m [38;5;66;03m# Demoscript for "Signalverarbeitung 1"[39;00m
[0;32m   (...)[0m
[1;32m      8[0m [38;5;66;03m# https://creativecommons.org/publicdomain/zero/1.0/[39;00m
[1;32m      9[0m [38;5;66;03m#-------------------------------------------------------------------------------[39;00m
[0;32m---> 11[0m [38;5;28;01mimport[39;00m [38;5;21;01myfinance[39;00m
[1;32m     12[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m
[1;32m     13[0m [38;5;28;01mfrom[39;00m [38;5;21;01mmatplotlib[39;00m [38;5;28;01mimport[39;00m pyplot

[0;31mModuleNotFoundError[0m: No module named 'yfinance'
ModuleNotFoundError: No module named 'yfinance'

